# ./docker-compose.yml

version: '3'

services:
  mysql:
    image: mysql8prueba2:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
        - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbphp
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    restart: always
  web:
    image: ubuntuapachephp7:4
    container_name: php_web
    depends_on:
      - mysql
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8080:80"
      - "2222:22"
    stdin_open: true
    tty: true
